services:

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 110321
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - micros_net

  carrito:
    build: ./carrito
    container_name: carrito
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 110321
    networks:
      - micros_net

  gestion_usuarios:
    build: ./gestion-usuarios
    container_name: gestion_usuarios
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 110321
    networks:
      - micros_net

  core_negocio:
    build: ./core_negocio
    container_name: core_negocio
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 110321
    networks:
      - micros_net

volumes:
  mysql_data:

networks:
  micros_net:
